<template><div><blockquote>
<p>Eventbus: Android optimized event bus that simplifies communication between Activities, Fragments, Threads, Services, etc. Less code, better quality.</p>
</blockquote>
<ol>
<li>官方网址:<a href="http://greenrobot.org/eventbus/" target="_blank" rel="noopener noreferrer">http://greenrobot.org/eventbus/<ExternalLinkIcon/></a></li>
<li>github:<a href="https://github.com/greenrobot/EventBus" target="_blank" rel="noopener noreferrer">https://github.com/greenrobot/EventBus<ExternalLinkIcon/></a></li>
<li>Eventbus结构，流程，核心类分析 <a href="http://a.codekk.com/detail/Android/Trinea/EventBus%20%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90" target="_blank" rel="noopener noreferrer">codekk分析<ExternalLinkIcon/></a></li>
<li><a href="https://github.com/pengqinping/Android.demo/tree/master/app.eventbus" target="_blank" rel="noopener noreferrer">自己测试demo<ExternalLinkIcon/></a></li>
</ol>
<h2 id="_1-eventbus-register-object-subcriber" tabindex="-1"><a class="header-anchor" href="#_1-eventbus-register-object-subcriber" aria-hidden="true">#</a> 1.EventBus.register(Object subcriber)</h2>
<blockquote>
<p>分析思路，以启动流程的逻辑来分析，没有任何前置条件。如果在越到变量值的问题，都以这个场景下的默认值带入</p>
</blockquote>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>
       <span class="token doc-comment comment">/**
     * Registers the given subscriber to receive events. Subscribers must call <span class="token punctuation">{</span><span class="token keyword">@link</span> <span class="token reference"><span class="token punctuation">#</span><span class="token function">unregister</span><span class="token punctuation">(</span><span class="token class-name">Object</span><span class="token punctuation">)</span></span><span class="token punctuation">}</span> once they
     * are no longer interested in receiving events.
     * <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span><span class="token punctuation">/></span></span>
     * Subscribers have event handling methods that must be annotated by <span class="token punctuation">{</span><span class="token keyword">@link</span> <span class="token reference"><span class="token class-name">Subscribe</span></span><span class="token punctuation">}</span>.
     * The <span class="token punctuation">{</span><span class="token keyword">@link</span> <span class="token reference"><span class="token class-name">Subscribe</span></span><span class="token punctuation">}</span> annotation also allows configuration like <span class="token punctuation">{</span><span class="token keyword">@link</span>
     * <span class="token reference"><span class="token class-name">ThreadMode</span></span><span class="token punctuation">}</span> and priority.
     * 中文：注册suberscriber对象将会收到消息，订阅者如果不想收到消息需要调用 <span class="token punctuation">{</span><span class="token keyword">@link</span> <span class="token reference"><span class="token punctuation">#</span><span class="token function">unregister</span><span class="token punctuation">(</span><span class="token class-name">Object</span><span class="token punctuation">)</span></span><span class="token punctuation">}</span> 方法取消,
     * 订阅者处理接受到的事件必须使用注解 <span class="token punctuation">{</span><span class="token keyword">@link</span> <span class="token reference"><span class="token class-name">Subscribe</span></span><span class="token punctuation">}</span> 来描述方法，
     * <span class="token punctuation">{</span><span class="token keyword">@link</span> <span class="token reference"><span class="token class-name">Subscribe</span></span><span class="token punctuation">}</span> 注解同样容许配置 <span class="token punctuation">{</span><span class="token keyword">@link</span>
     * <span class="token reference"><span class="token class-name">ThreadMode</span></span><span class="token punctuation">}</span> 和 优先级
     */</span>
    <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">register</span><span class="token punctuation">(</span><span class="token class-name">Object</span> subscriber<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// subsriberClass 表示订阅者对象的 class</span>
        <span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span> subscriberClass <span class="token operator">=</span> subscriber<span class="token punctuation">.</span><span class="token function">getClass</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// 对应 subscriberClass 所有 可以接受发布者发布的消息 的有 Subscribe 注解的方法的集合。</span>
        <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">SubscriberMethod</span><span class="token punctuation">></span></span> subscriberMethods <span class="token operator">=</span> subscriberMethodFinder<span class="token punctuation">.</span><span class="token function">findSubscriberMethods</span><span class="token punctuation">(</span>subscriberClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">synchronized</span> <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token class-name">SubscriberMethod</span> subscriberMethod <span class="token operator">:</span> subscriberMethods<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token function">subscribe</span><span class="token punctuation">(</span>subscriber<span class="token punctuation">,</span> subscriberMethod<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>首先看到订阅者接受消息的方法集合通过 <code v-pre>subscriberMethodFinder.findSubscriberMethods</code> 来获取，我们看看<strong>subscriberMethodFinder</strong> 对象的实例化, 是在 <em>EventBus</em> 的构造器中进行注册的并且接受了 builer中的3个参数 <code>builder.subscriberInfoIndexes</code> , <code> builder.strictMethodVerification</code> , <code>builder.ignoreGeneratedIndex</code> <em>EventBusBuilder</em> 实例是个什么东东，看看就知道，<strong>DEFAULT_BUILDER</strong> 是个静态实例, <code> private static final EventBusBuilder DEFAULT_BUILDER = new EventBusBuilder();</code></p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>
    <span class="token keyword">public</span> <span class="token class-name">EventBus</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">this</span><span class="token punctuation">(</span><span class="token constant">DEFAULT_BUILDER</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token class-name">EventBus</span><span class="token punctuation">(</span><span class="token class-name">EventBusBuilder</span> builder<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        subscriptionsByEventType <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">HashMap</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        typesBySubscriber <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">HashMap</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        stickyEvents <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ConcurrentHashMap</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        mainThreadPoster <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">HandlerPoster</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> <span class="token class-name">Looper</span><span class="token punctuation">.</span><span class="token function">getMainLooper</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        backgroundPoster <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">BackgroundPoster</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        asyncPoster <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">AsyncPoster</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        indexCount <span class="token operator">=</span> builder<span class="token punctuation">.</span>subscriberInfoIndexes <span class="token operator">!=</span> <span class="token keyword">null</span> <span class="token operator">?</span> builder<span class="token punctuation">.</span>subscriberInfoIndexes<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">;</span>
        subscriberMethodFinder <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">SubscriberMethodFinder</span><span class="token punctuation">(</span>builder<span class="token punctuation">.</span>subscriberInfoIndexes<span class="token punctuation">,</span>
                builder<span class="token punctuation">.</span>strictMethodVerification<span class="token punctuation">,</span> builder<span class="token punctuation">.</span>ignoreGeneratedIndex<span class="token punctuation">)</span><span class="token punctuation">;</span>
        logSubscriberExceptions <span class="token operator">=</span> builder<span class="token punctuation">.</span>logSubscriberExceptions<span class="token punctuation">;</span>
        logNoSubscriberMessages <span class="token operator">=</span> builder<span class="token punctuation">.</span>logNoSubscriberMessages<span class="token punctuation">;</span>
        sendSubscriberExceptionEvent <span class="token operator">=</span> builder<span class="token punctuation">.</span>sendSubscriberExceptionEvent<span class="token punctuation">;</span>
        sendNoSubscriberEvent <span class="token operator">=</span> builder<span class="token punctuation">.</span>sendNoSubscriberEvent<span class="token punctuation">;</span>
        throwSubscriberException <span class="token operator">=</span> builder<span class="token punctuation">.</span>throwSubscriberException<span class="token punctuation">;</span>
        eventInheritance <span class="token operator">=</span> builder<span class="token punctuation">.</span>eventInheritance<span class="token punctuation">;</span>
        executorService <span class="token operator">=</span> builder<span class="token punctuation">.</span>executorService<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>继续看看 <em>SubscriberMethodFinder</em> 的构造器中初始化了那些东西，那些是需要获取 <strong>subscriberMethods</strong> 这个集合使用的 首先看看入参值，参数值来源于 <em>EventBusBuiler</em> 的 <strong>DEFAULT_BUILDER</strong> 对象 so <strong>DEFAULT_BUILDER</strong>  的取值如下</p>
<ol>
<li><code>builder.subscriberInfoIndexes = null,</code></li>
<li><code>builder.strictMethodVerification = false;</code></li>
<li><code>builder.ignoreGeneratedIndex = false;</code></li>
</ol>
<p>那么 <code>EnventBus.getDefault().subscriberMethodFinder 取值</code> 注意其中 strictMethodVerification,ignoreGeneratedIndex 为 final修饰，所以这里就固定了它的取值</p>
<ol>
<li><code>subscriberMethodFinder.subscriberInfoIndexes = null,</code></li>
<li><code>subscriberMethodFinder.strictMethodVerification = false;</code></li>
<li><code>subscriberMethodFinder.ignoreGeneratedIndex = false;</code></li>
</ol>
<h4 id="_2-subscribermethodfinder-findsubscribermethods-class-subscriberclass" tabindex="-1"><a class="header-anchor" href="#_2-subscribermethodfinder-findsubscribermethods-class-subscriberclass" aria-hidden="true">#</a> 2.SubscriberMethodFinder.findSubscriberMethods(Class&lt;?&gt; subscriberClass)</h4>
<blockquote>
<p>调用这个方法开始，才开始查找的第一步，<strong>findSubscriberMethods</strong> 中也仅仅是做了缓存读取，和空判断，以及从其他方法获取结果后存入缓存，其中有两种方式获取 <strong>subscriberMethods</strong> 的方式，两种方式的区别会在稍后解答。</p>
</blockquote>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>
 <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">SubscriberMethod</span><span class="token punctuation">></span></span> <span class="token function">findSubscriberMethods</span><span class="token punctuation">(</span><span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span> subscriberClass<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">//第一次进入肯定没有缓存，需要关心放到缓冲中的东西是什么，怎么来的？</span>
        <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">SubscriberMethod</span><span class="token punctuation">></span></span> subscriberMethods <span class="token operator">=</span> <span class="token constant">METHOD_CACHE</span><span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>subscriberClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>subscriberMethods <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> subscriberMethods<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>

        <span class="token comment">//根据前置条件，这里第一次为false，可以看到我们通过这里就能获取到了 SubscriberMethod的集合</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>ignoreGeneratedIndex<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            subscriberMethods <span class="token operator">=</span> <span class="token function">findUsingReflection</span><span class="token punctuation">(</span>subscriberClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            subscriberMethods <span class="token operator">=</span> <span class="token function">findUsingInfo</span><span class="token punctuation">(</span>subscriberClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>subscriberMethods<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">EventBusException</span><span class="token punctuation">(</span><span class="token string">"Subscriber "</span> <span class="token operator">+</span> subscriberClass
                    <span class="token operator">+</span> <span class="token string">" and its super classes have no public methods with the @Subscribe annotation"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            <span class="token constant">METHOD_CACHE</span><span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span>subscriberClass<span class="token punctuation">,</span> subscriberMethods<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">return</span> subscriberMethods<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

      <span class="token keyword">private</span> <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">SubscriberMethod</span><span class="token punctuation">></span></span> <span class="token function">findUsingInfo</span><span class="token punctuation">(</span><span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span> subscriberClass<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token class-name">FindState</span> findState <span class="token operator">=</span> <span class="token function">prepareFindState</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        findState<span class="token punctuation">.</span><span class="token function">initForSubscriber</span><span class="token punctuation">(</span>subscriberClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">while</span> <span class="token punctuation">(</span>findState<span class="token punctuation">.</span>clazz <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token comment">//通过判断这里一般情况下 获取的 findState.subscriberInfo == null;</span>
            findState<span class="token punctuation">.</span>subscriberInfo <span class="token operator">=</span> <span class="token function">getSubscriberInfo</span><span class="token punctuation">(</span>findState<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>findState<span class="token punctuation">.</span>subscriberInfo <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token class-name">SubscriberMethod</span><span class="token punctuation">[</span><span class="token punctuation">]</span> array <span class="token operator">=</span> findState<span class="token punctuation">.</span>subscriberInfo<span class="token punctuation">.</span><span class="token function">getSubscriberMethods</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token class-name">SubscriberMethod</span> subscriberMethod <span class="token operator">:</span> array<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                    <span class="token keyword">if</span> <span class="token punctuation">(</span>findState<span class="token punctuation">.</span><span class="token function">checkAdd</span><span class="token punctuation">(</span>subscriberMethod<span class="token punctuation">.</span>method<span class="token punctuation">,</span> subscriberMethod<span class="token punctuation">.</span>eventType<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                        findState<span class="token punctuation">.</span>subscriberMethods<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span>subscriberMethod<span class="token punctuation">)</span><span class="token punctuation">;</span>
                    <span class="token punctuation">}</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
                <span class="token function">findUsingReflectionInSingleClass</span><span class="token punctuation">(</span>findState<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            findState<span class="token punctuation">.</span><span class="token function">moveToSuperclass</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">return</span> <span class="token function">getMethodsAndRelease</span><span class="token punctuation">(</span>findState<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>So ,一般情况下我们都是通过 findUsingReflectionInSingleClass 这个方法去获取订阅者中，接受订阅消息的方法。 oh oh oh  真正的操作应该就是 <strong>findUsingReflectionInSingleClass</strong> 这个方法中了，果然也是通过反射机制，首先关于getDeclaredMethods()自行调试看下就知道是那些方法了。</p>
</blockquote>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>
<span class="token keyword">private</span> <span class="token keyword">void</span> <span class="token function">findUsingReflectionInSingleClass</span><span class="token punctuation">(</span><span class="token class-name">FindState</span> findState<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token class-name">Method</span><span class="token punctuation">[</span><span class="token punctuation">]</span> methods<span class="token punctuation">;</span>
        <span class="token keyword">try</span> <span class="token punctuation">{</span>
            <span class="token comment">// This is faster than getMethods, especially when subscribers are fat classes like Activities</span>
            <span class="token comment">// findState.class == subscriberClass , about getDeclaredMethods method using baidu.com and google</span>
            methods <span class="token operator">=</span> findState<span class="token punctuation">.</span>clazz<span class="token punctuation">.</span><span class="token function">getDeclaredMethods</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span><span class="token class-name">Throwable</span> th<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token comment">// Workaround for java.lang.NoClassDefFoundError, see https://github.com/greenrobot/EventBus/issues/149</span>
            methods <span class="token operator">=</span> findState<span class="token punctuation">.</span>clazz<span class="token punctuation">.</span><span class="token function">getMethods</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            findState<span class="token punctuation">.</span>skipSuperClasses <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token class-name">Method</span> method <span class="token operator">:</span> methods<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">int</span> modifiers <span class="token operator">=</span> method<span class="token punctuation">.</span><span class="token function">getModifiers</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token comment">//两个为操作符保证了方法的修饰符必须是 public, and non-static and non-abstract,</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token punctuation">(</span>modifiers <span class="token operator">&amp;</span> <span class="token class-name">Modifier</span><span class="token punctuation">.</span><span class="token constant">PUBLIC</span><span class="token punctuation">)</span> <span class="token operator">!=</span> <span class="token number">0</span> <span class="token operator">&amp;&amp;</span> <span class="token punctuation">(</span>modifiers <span class="token operator">&amp;</span> <span class="token constant">MODIFIERS_IGNORE</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token comment">//方法的参数类型集合</span>
                <span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span><span class="token punctuation">[</span><span class="token punctuation">]</span> parameterTypes <span class="token operator">=</span> method<span class="token punctuation">.</span><span class="token function">getParameterTypes</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token comment">//原则上只能有一个参数，所以这个参数一般是 消息载体 Event,也可以叫做订阅消息。</span>
                <span class="token keyword">if</span> <span class="token punctuation">(</span>parameterTypes<span class="token punctuation">.</span>length <span class="token operator">==</span> <span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                    <span class="token comment">//获取方法的注解描述</span>
                    <span class="token class-name">Subscribe</span> subscribeAnnotation <span class="token operator">=</span> method<span class="token punctuation">.</span><span class="token function">getAnnotation</span><span class="token punctuation">(</span><span class="token class-name">Subscribe</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                    <span class="token keyword">if</span> <span class="token punctuation">(</span>subscribeAnnotation <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                        <span class="token comment">//eventType表示事件类型</span>
                        <span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span> eventType <span class="token operator">=</span> parameterTypes<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
                        <span class="token keyword">if</span> <span class="token punctuation">(</span>findState<span class="token punctuation">.</span><span class="token function">checkAdd</span><span class="token punctuation">(</span>method<span class="token punctuation">,</span> eventType<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                            <span class="token comment">//获取线程，findState.chackAdd的时候只有在第一次检测的时候才会返回true,其他时候都是false</span>
                            <span class="token class-name">ThreadMode</span> threadMode <span class="token operator">=</span> subscribeAnnotation<span class="token punctuation">.</span><span class="token function">threadMode</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                            <span class="token comment">//这里终于创建了 SubscriberMethod 对象，并且放到了 findState对象中的 subscriberMethods 中。</span>
                            findState<span class="token punctuation">.</span>subscriberMethods<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">SubscriberMethod</span><span class="token punctuation">(</span>method<span class="token punctuation">,</span> eventType<span class="token punctuation">,</span> threadMode<span class="token punctuation">,</span>
                                    subscribeAnnotation<span class="token punctuation">.</span><span class="token function">priority</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> subscribeAnnotation<span class="token punctuation">.</span><span class="token function">sticky</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                        <span class="token punctuation">}</span>
                    <span class="token punctuation">}</span>
                <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>strictMethodVerification <span class="token operator">&amp;&amp;</span> method<span class="token punctuation">.</span><span class="token function">isAnnotationPresent</span><span class="token punctuation">(</span><span class="token class-name">Subscribe</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                    <span class="token class-name">String</span> methodName <span class="token operator">=</span> method<span class="token punctuation">.</span><span class="token function">getDeclaringClass</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getName</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">"."</span> <span class="token operator">+</span> method<span class="token punctuation">.</span><span class="token function">getName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                    <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">EventBusException</span><span class="token punctuation">(</span><span class="token string">"@Subscribe method "</span> <span class="token operator">+</span> methodName <span class="token operator">+</span>
                            <span class="token string">"must have exactly 1 parameter but has "</span> <span class="token operator">+</span> parameterTypes<span class="token punctuation">.</span>length<span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>strictMethodVerification <span class="token operator">&amp;&amp;</span> method<span class="token punctuation">.</span><span class="token function">isAnnotationPresent</span><span class="token punctuation">(</span><span class="token class-name">Subscribe</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token class-name">String</span> methodName <span class="token operator">=</span> method<span class="token punctuation">.</span><span class="token function">getDeclaringClass</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getName</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">"."</span> <span class="token operator">+</span> method<span class="token punctuation">.</span><span class="token function">getName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">EventBusException</span><span class="token punctuation">(</span>methodName <span class="token operator">+</span>
                        <span class="token string">" is a illegal @Subscribe method: must be public, non-static, and non-abstract"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>


</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_2-eventbus-subscribe-object-subscriber-subscribermethod-subscribermethod" tabindex="-1"><a class="header-anchor" href="#_2-eventbus-subscribe-object-subscriber-subscribermethod-subscribermethod" aria-hidden="true">#</a> 2.EventBus.subscribe(Object subscriber,SubscriberMethod subscriberMethod);</h4>
<p>通过注解拿到所有的消息接受的方法后，这里遍历所有的 subcriberMethods, 调用EventBus.subcriber开始注册，是在register开始完成的。</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>
 <span class="token comment">// Must be called in synchronized block</span>
    <span class="token keyword">private</span> <span class="token keyword">void</span> <span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token class-name">Object</span> subscriber<span class="token punctuation">,</span> <span class="token class-name">SubscriberMethod</span> subscriberMethod<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">//eventType 这里指的是 接受订阅消息的方法的方法中的参数类型。</span>
        <span class="token comment">//例如  在下面的方法中 eventType = MessageEvent.class</span>
        <span class="token comment">/*
        @Subscribe
        public void onMessageEvent(MessageEvent event){
            Toast.makeText(getApplicationContext(),"received message "+event.message,Toast.LENGTH_LONG).show();
        }*/</span>
        <span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span> eventType <span class="token operator">=</span> subscriberMethod<span class="token punctuation">.</span>eventType<span class="token punctuation">;</span>
        <span class="token comment">//Subscription 是订阅对象，包涵了 subscriber:订阅者类，subscriberMethod:接受订阅消息的方法，</span>
        <span class="token class-name">Subscription</span> newSubscription <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Subscription</span><span class="token punctuation">(</span>subscriber<span class="token punctuation">,</span> subscriberMethod<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">//通过类型获取到，类型相关的多有的 Subcription对象集合，</span>
        <span class="token class-name">CopyOnWriteArrayList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Subscription</span><span class="token punctuation">></span></span> subscriptions <span class="token operator">=</span> subscriptionsByEventType<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>eventType<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>subscriptions <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token comment">//没有的时候才去加入，有的话直接报错，这里说明了一个问题，如果同一个订阅中出现两个接受订阅消息的方法的参数的类型是一样的会报错，:) 这都发现了，天才啊。</span>
            subscriptions <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">CopyOnWriteArrayList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            subscriptionsByEventType<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span>eventType<span class="token punctuation">,</span> subscriptions<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>subscriptions<span class="token punctuation">.</span><span class="token function">contains</span><span class="token punctuation">(</span>newSubscription<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">EventBusException</span><span class="token punctuation">(</span><span class="token string">"Subscriber "</span> <span class="token operator">+</span> subscriber<span class="token punctuation">.</span><span class="token function">getClass</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">" already registered to event "</span>
                        <span class="token operator">+</span> eventType<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>

        <span class="token keyword">int</span> size <span class="token operator">=</span> subscriptions<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">//这里size = 0 ,但是for循环会执行一次，恰好里面的if是可以执行的。 这样subscriptionsByEventType中的 subscriptions 就有值了。</span>
        <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">int</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;=</span> size<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>i <span class="token operator">==</span> size <span class="token operator">||</span> subscriberMethod<span class="token punctuation">.</span>priority <span class="token operator">></span> subscriptions<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">.</span>subscriberMethod<span class="token punctuation">.</span>priority<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                subscriptions<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span>i<span class="token punctuation">,</span> newSubscription<span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token keyword">break</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>

        <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Class</span><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span><span class="token punctuation">></span></span> subscribedEvents <span class="token operator">=</span> typesBySubscriber<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>subscriber<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>subscribedEvents <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            subscribedEvents <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ArrayList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            typesBySubscriber<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span>subscriber<span class="token punctuation">,</span> subscribedEvents<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        subscribedEvents<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span>eventType<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">//只有添加了 sticky注解的才有走这里， sticky 是做什么的呢？</span>
        <span class="token comment">//Sticky 事件不同之处在于，当事件发布后，再有订阅者开始订阅该类型事件，依然能收到该类型事件最近一个 Sticky 事件。</span>
        <span class="token comment">//所以这里如果是 sticky事件，这里就开始发送给订阅者，即使还没有post(event) 这里的event那里来的呢？sticky 的意义就来了，他是发布事件后，在有订阅者</span>
        <span class="token comment">//也就是 之前就应该有发布过事件，这里是能够取到事件对象的。</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>subscriberMethod<span class="token punctuation">.</span>sticky<span class="token punctuation">)</span> <span class="token punctuation">{</span>

            <span class="token keyword">if</span> <span class="token punctuation">(</span>eventInheritance<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token comment">// Existing sticky events of all subclasses of eventType have to be considered.</span>
                <span class="token comment">// Note: Iterating over all events may be inefficient with lots of sticky events,</span>
                <span class="token comment">// thus data structure should be changed to allow a more efficient lookup</span>
                <span class="token comment">// (e.g. an additional map storing sub classes of super classes: Class -> List&lt;Class>).</span>
                <span class="token class-name">Set</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Map<span class="token punctuation">.</span>Entry</span><span class="token punctuation">&lt;</span><span class="token class-name">Class</span><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span><span class="token punctuation">,</span> <span class="token class-name">Object</span><span class="token punctuation">></span><span class="token punctuation">></span></span> entries <span class="token operator">=</span> stickyEvents<span class="token punctuation">.</span><span class="token function">entrySet</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token class-name">Map<span class="token punctuation">.</span>Entry</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Class</span><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span><span class="token punctuation">,</span> <span class="token class-name">Object</span><span class="token punctuation">></span></span> entry <span class="token operator">:</span> entries<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                    <span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span> candidateEventType <span class="token operator">=</span> entry<span class="token punctuation">.</span><span class="token function">getKey</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                    <span class="token keyword">if</span> <span class="token punctuation">(</span>eventType<span class="token punctuation">.</span><span class="token function">isAssignableFrom</span><span class="token punctuation">(</span>candidateEventType<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                        <span class="token class-name">Object</span> stickyEvent <span class="token operator">=</span> entry<span class="token punctuation">.</span><span class="token function">getValue</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                        <span class="token function">checkPostStickyEventToSubscription</span><span class="token punctuation">(</span>newSubscription<span class="token punctuation">,</span> stickyEvent<span class="token punctuation">)</span><span class="token punctuation">;</span>
                    <span class="token punctuation">}</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
                <span class="token class-name">Object</span> stickyEvent <span class="token operator">=</span> stickyEvents<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>eventType<span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token function">checkPostStickyEventToSubscription</span><span class="token punctuation">(</span>newSubscription<span class="token punctuation">,</span> stickyEvent<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_3-eventbus-post-object-subcriber" tabindex="-1"><a class="header-anchor" href="#_3-eventbus-post-object-subcriber" aria-hidden="true">#</a> 3.EventBus.post(Object subcriber)</h4>
<p>到这一步后订阅者所有的接受消息的方法都放在了<strong>subscriberMethods</strong>中，所以接下来继续分析 发送消息的流程。post的机制就比较简单了，在 post方法中做了一个简单的线程安全的控制然后遍历 队列，通过 <strong>postSingleEvent</strong>来处理单个消息。</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>
 <span class="token keyword">private</span> <span class="token keyword">void</span> <span class="token function">postSingleEvent</span><span class="token punctuation">(</span><span class="token class-name">Object</span> event<span class="token punctuation">,</span> <span class="token class-name">PostingThreadState</span> postingState<span class="token punctuation">)</span> <span class="token keyword">throws</span> <span class="token class-name">Error</span> <span class="token punctuation">{</span>
        <span class="token comment">//这里的event就是消息，</span>
        <span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span> eventClass <span class="token operator">=</span> event<span class="token punctuation">.</span><span class="token function">getClass</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">boolean</span> subscriptionFound <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
        <span class="token comment">//默认的Builde对象中，eventInheritance = true;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>eventInheritance<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token comment">//获取</span>
            <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Class</span><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span><span class="token punctuation">></span></span> eventTypes <span class="token operator">=</span> <span class="token function">lookupAllEventTypes</span><span class="token punctuation">(</span>eventClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">int</span> countTypes <span class="token operator">=</span> eventTypes<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">int</span> h <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> h <span class="token operator">&lt;</span> countTypes<span class="token punctuation">;</span> h<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token operator">?</span><span class="token punctuation">></span></span> clazz <span class="token operator">=</span> eventTypes<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>h<span class="token punctuation">)</span><span class="token punctuation">;</span>
                subscriptionFound <span class="token operator">|=</span> <span class="token function">postSingleEventForEventType</span><span class="token punctuation">(</span>event<span class="token punctuation">,</span> postingState<span class="token punctuation">,</span> clazz<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            subscriptionFound <span class="token operator">=</span> <span class="token function">postSingleEventForEventType</span><span class="token punctuation">(</span>event<span class="token punctuation">,</span> postingState<span class="token punctuation">,</span> eventClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>subscriptionFound<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>logNoSubscriberMessages<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token class-name">Log</span><span class="token punctuation">.</span><span class="token function">d</span><span class="token punctuation">(</span><span class="token constant">TAG</span><span class="token punctuation">,</span> <span class="token string">"No subscribers registered for event "</span> <span class="token operator">+</span> eventClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>sendNoSubscriberEvent <span class="token operator">&amp;&amp;</span> eventClass <span class="token operator">!=</span> <span class="token class-name">NoSubscriberEvent</span><span class="token punctuation">.</span><span class="token keyword">class</span> <span class="token operator">&amp;&amp;</span>
                    eventClass <span class="token operator">!=</span> <span class="token class-name">SubscriberExceptionEvent</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token function">post</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">NoSubscriberEvent</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> event<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>最终是通过反射的方式来实现的。</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>
<span class="token comment">//使用反射的方法调用 订阅消息的接受者，并且传入 event 对象</span>
    <span class="token keyword">void</span> <span class="token function">invokeSubscriber</span><span class="token punctuation">(</span><span class="token class-name">Subscription</span> subscription<span class="token punctuation">,</span> <span class="token class-name">Object</span> event<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">try</span> <span class="token punctuation">{</span>
            subscription<span class="token punctuation">.</span>subscriberMethod<span class="token punctuation">.</span>method<span class="token punctuation">.</span><span class="token function">invoke</span><span class="token punctuation">(</span>subscription<span class="token punctuation">.</span>subscriber<span class="token punctuation">,</span> event<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span><span class="token class-name">InvocationTargetException</span> e<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token function">handleSubscriberException</span><span class="token punctuation">(</span>subscription<span class="token punctuation">,</span> event<span class="token punctuation">,</span> e<span class="token punctuation">.</span><span class="token function">getCause</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span><span class="token class-name">IllegalAccessException</span> e<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">IllegalStateException</span><span class="token punctuation">(</span><span class="token string">"Unexpected exception"</span><span class="token punctuation">,</span> e<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


