<template><div><h1 id="paging" tabindex="-1"><a class="header-anchor" href="#paging" aria-hidden="true">#</a> Paging</h1>
<ul>
<li>Google 文档 https://developer.android.google.cn/topic/libraries/architecture/paging</li>
<li>Github项目：https://github.com/android/architecture-components-samples/tree/master/PagingSample</li>
<li>Gitee项目：https://gitee.com/pengqinping/architecture-components-samples/tree/master/PagingSample (developer 改 maven repo 为 ali )</li>
</ul>
<div style='background:#fff5f5; color:#ff502c; display:block; font-size: 14px; margin: 16px 0;padding: 10px; border-radius:5px;border: 1px #f97d64 dashed'> 开始前先问自己几个问题：<br/>1. 官方介绍说是用来做按需加载？那么和以前的 自己写的分页加载(根据页面判断数据是加在data列表的头还是尾)有什么区别<br/>2. Paging 解决的问题是什么？ 优势是什么？</div>
<h2 id="代码分析" tabindex="-1"><a class="header-anchor" href="#代码分析" aria-hidden="true">#</a> 代码分析</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 继承于列表，那就是当做 data列表用</span>
<span class="token comment">// 加入了 刷新，开始，介绍 三种类型，每种类型都对应下面的五种状态</span>
<span class="token comment">// 这不是分页熟悉的逻辑吗，只不过以前是封装在View层的，</span>
<span class="token keyword">public</span> <span class="token keyword">abstract</span> <span class="token keyword">class</span> <span class="token class-name">PagedList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span><span class="token punctuation">></span></span> <span class="token keyword">extends</span> <span class="token class-name">AbstractList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span><span class="token punctuation">></span></span><span class="token punctuation">{</span>
   <span class="token keyword">public</span> <span class="token keyword">enum</span> <span class="token class-name">LoadType</span> <span class="token punctuation">{</span> <span class="token constant">REFRESH</span><span class="token punctuation">,</span> <span class="token constant">START</span><span class="token punctuation">,</span> <span class="token constant">END</span> <span class="token punctuation">}</span>
   <span class="token keyword">public</span> <span class="token keyword">enum</span> <span class="token class-name">LoadState</span> <span class="token punctuation">{</span> <span class="token constant">IDLE</span><span class="token punctuation">,</span> <span class="token constant">LOADING</span><span class="token punctuation">,</span> <span class="token constant">DONE</span><span class="token punctuation">,</span> <span class="token constant">ERROR</span><span class="token punctuation">,</span> <span class="token constant">RETRYABLE_ERROR</span> <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token comment">// 构造器</span>
<span class="token class-name">PagedList</span><span class="token punctuation">(</span><span class="token annotation punctuation">@NonNull</span> <span class="token class-name">PagedStorage</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span><span class="token punctuation">></span></span> storage<span class="token punctuation">,</span>
        <span class="token annotation punctuation">@NonNull</span> <span class="token class-name">Executor</span> mainThreadExecutor<span class="token punctuation">,</span>
        <span class="token annotation punctuation">@NonNull</span> <span class="token class-name">Executor</span> backgroundThreadExecutor<span class="token punctuation">,</span>
        <span class="token annotation punctuation">@Nullable</span> <span class="token class-name">BoundaryCallback</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span><span class="token punctuation">></span></span> boundaryCallback<span class="token punctuation">,</span>
        <span class="token annotation punctuation">@NonNull</span> <span class="token class-name">Config</span> config<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    mStorage <span class="token operator">=</span> storage<span class="token punctuation">;</span> <span class="token comment">// ContiguousPageList 和 TiledPagedList 默认值都是 new PagedStorage&lt;V>() </span>
    mMainThreadExecutor <span class="token operator">=</span> mainThreadExecutor<span class="token punctuation">;</span> <span class="token comment">// ui线程池 默认值  ArchTaskExecutor.getMainThreadExecutor()</span>
    mBackgroundThreadExecutor <span class="token operator">=</span> backgroundThreadExecutor<span class="token punctuation">;</span> <span class="token comment">// 耗时线程池 默认值： ArchTaskExecutor.getIOThreadExecutor()</span>
    mBoundaryCallback <span class="token operator">=</span> boundaryCallback<span class="token punctuation">;</span> <span class="token comment">// 回调 传入</span>
    mConfig <span class="token operator">=</span> config<span class="token punctuation">;</span> <span class="token comment">// 分页配置 一般是传入</span>
    mRequiredRemainder <span class="token operator">=</span> mConfig<span class="token punctuation">.</span>prefetchDistance <span class="token operator">*</span> <span class="token number">2</span> <span class="token operator">+</span> mConfig<span class="token punctuation">.</span>pageSize<span class="token punctuation">;</span>
<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="pagingsample-项目解读" tabindex="-1"><a class="header-anchor" href="#pagingsample-项目解读" aria-hidden="true">#</a> PagingSample 项目解读</h2>
<p>看了基本的结构，接下来 看如如何使用，既然是<code v-pre>Pagin</code>是M层，那么必定是在<code v-pre>ViewModel</code>里面使用，配合<code v-pre>LiveData</code>来实现可观察 实时刷新</p>
<ol>
<li>先看数据源</li>
</ol>
<div class="language-kotlin line-numbers-mode" data-ext="kt"><pre v-pre class="language-kotlin"><code><span class="token annotation builtin">@Query</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"SELECT * FROM Cheese ORDER BY name COLLATE NOCASE ASC"</span></span><span class="token punctuation">)</span>
<span class="token keyword">fun</span> <span class="token function">allCheesesByName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> DataSource<span class="token punctuation">.</span>Factory<span class="token operator">&lt;</span>Int<span class="token punctuation">,</span> Cheese<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>他没有直接返回 <code v-pre>PagedList</code> 而是返回了一个 <code v-pre>DataSource.Factory</code>， 在 <code v-pre>LivePagedList</code> 扩展了一个  <code v-pre>DataSource.Factory&lt;Key, Value&gt;.toLiveData(config...)</code> 的函数 用来返回 <code v-pre>LiveData</code> 类型的 <code v-pre>PagedList</code></p>
<p><strong>CheeseDao_Impl.java</strong> 中具体的  <code v-pre>DataSource.Factory</code> 实现类
直接 new 了 一个匿名的抽象来 来返回一个 <code v-pre>LimitOffsetDataSource&lt;Cheese&gt;</code></p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token annotation punctuation">@Override</span>
<span class="token keyword">public</span> <span class="token class-name">DataSource<span class="token punctuation">.</span>Factory</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Integer</span><span class="token punctuation">,</span> <span class="token class-name">Cheese</span><span class="token punctuation">></span></span> <span class="token function">allCheesesByName</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
<span class="token keyword">final</span> <span class="token class-name">String</span> _sql <span class="token operator">=</span> <span class="token string">"SELECT * FROM Cheese ORDER BY name COLLATE NOCASE ASC"</span><span class="token punctuation">;</span>
<span class="token keyword">final</span> <span class="token class-name">RoomSQLiteQuery</span> _statement <span class="token operator">=</span> <span class="token class-name">RoomSQLiteQuery</span><span class="token punctuation">.</span><span class="token function">acquire</span><span class="token punctuation">(</span>_sql<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">return</span> <span class="token keyword">new</span> <span class="token class-name">DataSource<span class="token punctuation">.</span>Factory</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Integer</span><span class="token punctuation">,</span> <span class="token class-name">Cheese</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> 
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token class-name">LimitOffsetDataSource</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Cheese</span><span class="token punctuation">></span></span> <span class="token function">create</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token keyword">new</span> <span class="token class-name">LimitOffsetDataSource</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Cheese</span><span class="token punctuation">></span></span><span class="token punctuation">(</span>__db<span class="token punctuation">,</span> _statement<span class="token punctuation">,</span> <span class="token boolean">false</span> <span class="token punctuation">,</span> <span class="token string">"Cheese"</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token annotation punctuation">@Override</span>
        <span class="token keyword">protected</span> <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Cheese</span><span class="token punctuation">></span></span> <span class="token function">convertRows</span><span class="token punctuation">(</span><span class="token class-name">Cursor</span> cursor<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">final</span> <span class="token keyword">int</span> _cursorIndexOfId <span class="token operator">=</span> <span class="token class-name">CursorUtil</span><span class="token punctuation">.</span><span class="token function">getColumnIndexOrThrow</span><span class="token punctuation">(</span>cursor<span class="token punctuation">,</span> <span class="token string">"id"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">final</span> <span class="token keyword">int</span> _cursorIndexOfName <span class="token operator">=</span> <span class="token class-name">CursorUtil</span><span class="token punctuation">.</span><span class="token function">getColumnIndexOrThrow</span><span class="token punctuation">(</span>cursor<span class="token punctuation">,</span> <span class="token string">"name"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">final</span> <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Cheese</span><span class="token punctuation">></span></span> _res <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ArrayList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Cheese</span><span class="token punctuation">></span></span><span class="token punctuation">(</span>cursor<span class="token punctuation">.</span><span class="token function">getCount</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">while</span><span class="token punctuation">(</span>cursor<span class="token punctuation">.</span><span class="token function">moveToNext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">final</span> <span class="token class-name">Cheese</span> _item<span class="token punctuation">;</span>
            <span class="token keyword">final</span> <span class="token keyword">int</span> _tmpId<span class="token punctuation">;</span>
            _tmpId <span class="token operator">=</span> cursor<span class="token punctuation">.</span><span class="token function">getInt</span><span class="token punctuation">(</span>_cursorIndexOfId<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">final</span> <span class="token class-name">String</span> _tmpName<span class="token punctuation">;</span>
            _tmpName <span class="token operator">=</span> cursor<span class="token punctuation">.</span><span class="token function">getString</span><span class="token punctuation">(</span>_cursorIndexOfName<span class="token punctuation">)</span><span class="token punctuation">;</span>
            _item <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Cheese</span><span class="token punctuation">(</span>_tmpId<span class="token punctuation">,</span>_tmpName<span class="token punctuation">)</span><span class="token punctuation">;</span>
            _res<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span>_item<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">return</span> _res<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="2">
<li><code v-pre>CheeseViewModel</code> 通过 <code v-pre>DataSource</code> 来返回 <code v-pre>LiveData&lt;PagedList&lt;Value&gt;&gt; </code></li>
</ol>
<div class="language-kotlin line-numbers-mode" data-ext="kt"><pre v-pre class="language-kotlin"><code><span class="token comment">// 传入一个Config，主要配置 没有的数量，大小等</span>
<span class="token keyword">val</span> allCheeses <span class="token operator">=</span> dao<span class="token punctuation">.</span><span class="token function">allCheesesByName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toLiveData</span><span class="token punctuation">(</span><span class="token function">Config</span><span class="token punctuation">(</span>pageSize<span class="token operator">=</span><span class="token number">60</span><span class="token punctuation">,</span> enablePlaceholders<span class="token operator">=</span><span class="token boolean">true</span><span class="token punctuation">,</span> maxSize<span class="token operator">=</span><span class="token number">200</span><span class="token punctuation">)</span><span class="token punctuation">)</span>

<span class="token comment">// Config 是通过 PagedList.Config.Builder 构建出来的</span>
<span class="token keyword">fun</span> <span class="token function">Config</span><span class="token punctuation">(</span>
    pageSize<span class="token operator">:</span> Int<span class="token punctuation">,</span>
    prefetchDistance<span class="token operator">:</span> Int <span class="token operator">=</span> pageSize<span class="token punctuation">,</span>
    enablePlaceholders<span class="token operator">:</span> Boolean <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
    initialLoadSizeHint<span class="token operator">:</span> Int <span class="token operator">=</span>
            pageSize <span class="token operator">*</span> PagedList<span class="token punctuation">.</span>Config<span class="token punctuation">.</span>Builder<span class="token punctuation">.</span>DEFAULT_INITIAL_PAGE_MULTIPLIER<span class="token punctuation">,</span>
    maxSize<span class="token operator">:</span> Int <span class="token operator">=</span> PagedList<span class="token punctuation">.</span>Config<span class="token punctuation">.</span>MAX_SIZE_UNBOUNDED
<span class="token punctuation">)</span><span class="token operator">:</span> PagedList<span class="token punctuation">.</span><span class="token function">Config</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> PagedList<span class="token punctuation">.</span>Config<span class="token punctuation">.</span><span class="token function">Builder</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">setPageSize</span><span class="token punctuation">(</span>pageSize<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">setPrefetchDistance</span><span class="token punctuation">(</span>prefetchDistance<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">setEnablePlaceholders</span><span class="token punctuation">(</span>enablePlaceholders<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">setInitialLoadSizeHint</span><span class="token punctuation">(</span>initialLoadSizeHint<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">setMaxSize</span><span class="token punctuation">(</span>maxSize<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">build</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="3">
<li>LimitOffsetDataSource<Cheese>.toLiveData() 直接带入实现类来分析</li>
</ol>
<div class="language-kotlin line-numbers-mode" data-ext="kt"><pre v-pre class="language-kotlin"><code><span class="token keyword">fun</span> <span class="token operator">&lt;</span>Key<span class="token punctuation">,</span> Value<span class="token operator">></span> DataSource<span class="token punctuation">.</span>Factory<span class="token operator">&lt;</span>Key<span class="token punctuation">,</span> Value<span class="token operator">></span><span class="token punctuation">.</span><span class="token function">toLiveData</span><span class="token punctuation">(</span>
    config<span class="token operator">:</span> PagedList<span class="token punctuation">.</span>Config<span class="token punctuation">,</span>
    initialLoadKey <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">,</span>
    boundaryCallback <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">,</span>
    fetchExecutor<span class="token operator">:</span> Executor <span class="token operator">=</span> ArchTaskExecutor<span class="token punctuation">.</span><span class="token function">getIOThreadExecutor</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token operator">:</span> LiveData<span class="token operator">&lt;</span>PagedList<span class="token operator">&lt;</span>Value<span class="token operator">></span><span class="token operator">></span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token function">LivePagedListBuilder</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> config<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">setInitialLoadKey</span><span class="token punctuation">(</span>initialLoadKey<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">setBoundaryCallback</span><span class="token punctuation">(</span>boundaryCallback<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">setFetchExecutor</span><span class="token punctuation">(</span>fetchExecutor<span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">build</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
<span class="token comment">// 经过下面一些列的封装主要做 两个事情</span>
<span class="token comment">// 1. 创建 LiveData</span>
<span class="token comment">// 2. 创建 PagedList </span>
LivePagedListBuilder<span class="token punctuation">.</span><span class="token function">build</span><span class="token punctuation">(</span><span class="token punctuation">)</span> 
LivePagedListBuilder<span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span>key<span class="token punctuation">,</span> PagedList<span class="token punctuation">.</span>Config<span class="token punctuation">,</span> PagedList<span class="token punctuation">.</span>BoundaryCallback<span class="token punctuation">,</span> DataSource<span class="token punctuation">.</span>Factory<span class="token operator">&lt;</span>Key<span class="token punctuation">,</span> Value<span class="token operator">></span><span class="token punctuation">,</span> Executor<span class="token punctuation">,</span> Executor<span class="token punctuation">)</span>

<span class="token comment">// LiveData 创建 : LiveData = new ComputableLiveData&lt;PagedList&lt;Value>>()</span>
<span class="token comment">// PagedList =  PagedList.Builder&lt;>().build()</span>
<span class="token comment">// PagedList 创建 : PagedList =  PagedList.Builder&lt;>().create(DataSource&lt;K, T>, Executor,Executor, BoundaryCallback, Config, Key )</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>PagedList 到底怎么把数据 add 到自己的列表的呢？
在<code v-pre>PagedList.create()</code>中 最终返回的是 <code v-pre>ContiguousPagedList</code> 或者 <code v-pre>TiledPagedList</code> 通过构造来创建的对象。</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// ContiguousDataSource 与 PositionalDataSource 这里我们可以带入 LimitOffsetDataSource 来分析</span>
 <span class="token class-name">ContiguousDataSource</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">K</span><span class="token punctuation">,</span> <span class="token class-name">T</span><span class="token punctuation">></span></span> contigDataSource <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token class-name">ContiguousDataSource</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">K</span><span class="token punctuation">,</span> <span class="token class-name">T</span><span class="token punctuation">></span></span><span class="token punctuation">)</span> dataSource<span class="token punctuation">;</span>
<span class="token keyword">return</span> <span class="token keyword">new</span> <span class="token class-name">ContiguousPagedList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span>contigDataSource<span class="token punctuation">,</span>
        notifyExecutor<span class="token punctuation">,</span>
        fetchExecutor<span class="token punctuation">,</span>
        boundaryCallback<span class="token punctuation">,</span>
        config<span class="token punctuation">,</span>
        key<span class="token punctuation">,</span>
        lastLoad<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">return</span> <span class="token keyword">new</span> <span class="token class-name">TiledPagedList</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token class-name">PositionalDataSource</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span><span class="token punctuation">></span></span><span class="token punctuation">)</span> dataSource<span class="token punctuation">,</span>
                notifyExecutor<span class="token punctuation">,</span>
                fetchExecutor<span class="token punctuation">,</span>
                boundaryCallback<span class="token punctuation">,</span>
                config<span class="token punctuation">,</span>
                <span class="token punctuation">(</span>key <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token operator">?</span> <span class="token punctuation">(</span><span class="token class-name">Integer</span><span class="token punctuation">)</span> key <span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>通过分析可知，最后调用到这里进行了 把 数据的数据 装载到了 List ，并且通过 Callback 返回了。
<code v-pre>LimitOffsetDataSource.loadInitial(LoadInitialParams params,LoadInitialCallback&lt;T&gt; callback)</code></p>
<ol start="4">
<li><code v-pre>LoadInitialCallbackImpl.OnResult()</code></li>
</ol>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token annotation punctuation">@Override</span>
<span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">onResult</span><span class="token punctuation">(</span><span class="token annotation punctuation">@NonNull</span> <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span><span class="token punctuation">></span></span> data<span class="token punctuation">,</span> <span class="token keyword">int</span> position<span class="token punctuation">,</span> <span class="token keyword">int</span> totalCount<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">//... some code</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>mCountingEnabled<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">int</span> trailingUnloadedCount <span class="token operator">=</span> totalCount <span class="token operator">-</span> position <span class="token operator">-</span> data<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        mCallbackHelper<span class="token punctuation">.</span><span class="token function">dispatchResultToReceiver</span><span class="token punctuation">(</span>
                <span class="token keyword">new</span> <span class="token class-name">PageResult</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> position<span class="token punctuation">,</span> trailingUnloadedCount<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
        <span class="token comment">// Only occurs when wrapped as contiguous</span>
        mCallbackHelper<span class="token punctuation">.</span><span class="token function">dispatchResultToReceiver</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">PageResult</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> position<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
     <span class="token comment">//... some code</span>
<span class="token punctuation">}</span>
<span class="token comment">// LoadCallbackHelper.dispatchOnCurrentThread()</span>
<span class="token keyword">void</span> <span class="token function">dispatchOnCurrentThread</span><span class="token punctuation">(</span><span class="token annotation punctuation">@Nullable</span> <span class="token class-name">PageResult</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span><span class="token punctuation">></span></span> result<span class="token punctuation">,</span>
        <span class="token annotation punctuation">@Nullable</span> <span class="token class-name">Throwable</span> error<span class="token punctuation">,</span> <span class="token keyword">boolean</span> retryable<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>result <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        mReceiver<span class="token punctuation">.</span><span class="token function">onPageResult</span><span class="token punctuation">(</span>mResultType<span class="token punctuation">,</span> result<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
        mReceiver<span class="token punctuation">.</span><span class="token function">onPageError</span><span class="token punctuation">(</span>mResultType<span class="token punctuation">,</span> error<span class="token punctuation">,</span> retryable<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="5">
<li>ContiguousPagedList.mReceiver or TiledPagedList.mReceiver
最终的 mReceiver 是定义在这两个实现类里面的
可以看到在这里对列表 进行了添加操作，以及 PagedList 一系列状态的管理。</li>
</ol>
<p>回答最开始的几个问题</p>
<ol>
<li>
<p>通过分析看到，以前自己写的刷新主要是通过 在 View 层进行控制，以及加载事件的处理 加载，刷新以及状态处理。 通过 PagedList 可以看到 这些加载逻辑全部放到了 M 层，数据变化后自动会去更新（只用于Room本地数据库）</p>
</li>
<li>
<p>在我的理解看来 它解决的主要是结合 MVVM框架而对M层在有批量加载的时候用来做分页处理，好处最明显的就是和本地数据库配合使用非常简单，易于扩张，如果你写过 分页逻辑，每个页面都是写一次 第一页 结束刷新，把数据加到头部，不是第一页把数据加到 列表尾部，结束加载更多，这个也许会成为你的菜。</p>
</li>
</ol>
</div></template>


