<template><div><h1 id="viewmodel-是怎样被创建的" tabindex="-1"><a class="header-anchor" href="#viewmodel-是怎样被创建的" aria-hidden="true">#</a> ViewModel 是怎样被创建的？</h1>
<h2 id="介绍" tabindex="-1"><a class="header-anchor" href="#介绍" aria-hidden="true">#</a> 介绍</h2>
<ul>
<li>Google介绍：<a href="https://developer.android.google.cn/topic/libraries/architecture/viewmodel" target="_blank" rel="noopener noreferrer">https://developer.android.google.cn/topic/libraries/architecture/viewmodel<ExternalLinkIcon/></a></li>
<li><span style='background-color:#FEEFE3;color:#BF350B;padding:3px'>Deprecated</span> <code v-pre>ViewModelProviders.of()</code> 该方法过期，使用 <code v-pre>new ViewModleProvider()</code> 来替换</li>
<li><code v-pre>ViewModelProvider</code> Documents: <a href="https://developer.android.google.cn/reference/androidx/lifecycle/ViewModelProvider?hl=en" target="_blank" rel="noopener noreferrer">https://developer.android.google.cn/reference/androidx/lifecycle/ViewModelProvider?hl=en<ExternalLinkIcon/></a></li>
</ul>
<h2 id="architecutre-项目-viewmodel-创建-分析" tabindex="-1"><a class="header-anchor" href="#architecutre-项目-viewmodel-创建-分析" aria-hidden="true">#</a> architecutre 项目 ViewModel 创建 分析</h2>
<p>ViewModel 是通过 ViewProvider 创建出来的</p>
<h3 id="viewmodelprovider" tabindex="-1"><a class="header-anchor" href="#viewmodelprovider" aria-hidden="true">#</a> <code v-pre>ViewModelProvider()</code></h3>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 构造器生成了两个对象， </span>
<span class="token comment">// Class的newInstance 来创建 ViewModel对象 fragment 和 Activity 返回的时 SavedStateViewModelFactory 的对象 </span>
<span class="token keyword">private</span> <span class="token keyword">final</span> <span class="token class-name">Factory</span> mFactory<span class="token punctuation">;</span> 
<span class="token comment">// 用来在Activity或者 Fragment 缓存 ViewModel用，如果有多个 ViewModel 就会进行缓存</span>
<span class="token keyword">private</span> <span class="token keyword">final</span> <span class="token class-name">ViewModelStore</span> mViewModelStore<span class="token punctuation">;</span>  
<span class="token comment">// 构造器</span>
 <span class="token keyword">public</span> <span class="token class-name">ViewModelProvider</span><span class="token punctuation">(</span><span class="token annotation punctuation">@NonNull</span> <span class="token class-name">ViewModelStoreOwner</span> owner<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">this</span><span class="token punctuation">(</span>owner<span class="token punctuation">.</span><span class="token function">getViewModelStore</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> owner <span class="token keyword">instanceof</span> <span class="token class-name">HasDefaultViewModelProviderFactory</span>
                <span class="token operator">?</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token class-name">HasDefaultViewModelProviderFactory</span><span class="token punctuation">)</span> owner<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getDefaultViewModelProviderFactory</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token operator">:</span> <span class="token class-name">NewInstanceFactory</span><span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li><code v-pre>ViewModelStoreOwner</code> 接口 <strong><code v-pre>getViewModelStore</code></strong> 用来返回 <code v-pre>ViewModelStore</code>对象， <code v-pre>Fragment</code> 和 <code v-pre>ComponentActivity</code> 中实现了此接口,</li>
<li><code v-pre>HasDefaultViewModelProviderFactory</code> 接口 <strong><code v-pre>getDefaultViewModelProviderFactory</code></strong> 就返回了一个 <code v-pre>factory</code>, <code v-pre>Fragment</code> 和 <code v-pre>ComponentActivity</code> 中实现了此接口</li>
<li><strong>由此可见ViewModel中的两个东西其实都在 <code v-pre>fragment</code> 或 <code v-pre>ComponentActivity</code>中返回的</strong></li>
</ul>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// Component.getViewModelStore()</span>
   <span class="token keyword">public</span> <span class="token class-name">ViewModelStore</span> <span class="token function">getViewModelStore</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token function">getApplication</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">IllegalStateException</span><span class="token punctuation">(</span><span class="token string">"Your activity is not yet attached to the "</span>
                    <span class="token operator">+</span> <span class="token string">"Application instance. You can't request ViewModel before onCreate call."</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>mViewModelStore <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token class-name">NonConfigurationInstances</span> nc <span class="token operator">=</span>
                    <span class="token punctuation">(</span><span class="token class-name">NonConfigurationInstances</span><span class="token punctuation">)</span> <span class="token function">getLastNonConfigurationInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>nc <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token comment">// Restore the ViewModelStore from NonConfigurationInstances</span>
                mViewModelStore <span class="token operator">=</span> nc<span class="token punctuation">.</span>viewModelStore<span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>mViewModelStore <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                mViewModelStore <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ViewModelStore</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">return</span> mViewModelStore<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

<span class="token comment">// FragmentManagerViewModel.getViewModelStore()</span>
 <span class="token class-name">ViewModelStore</span> <span class="token function">getViewModelStore</span><span class="token punctuation">(</span><span class="token annotation punctuation">@NonNull</span> <span class="token class-name">Fragment</span> f<span class="token punctuation">)</span> <span class="token punctuation">{</span>
     <span class="token comment">// mViewModelStores 是 一个Map 用来存放 viewModel, FragmentManager 可以存放多个fragment </span>
     <span class="token comment">// mWho =  UUID.randomUUID().toString();frament 标示</span>
        <span class="token class-name">ViewModelStore</span> viewModelStore <span class="token operator">=</span> mViewModelStores<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>f<span class="token punctuation">.</span>mWho<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>viewModelStore <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            viewModelStore <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ViewModelStore</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            mViewModelStores<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span>f<span class="token punctuation">.</span>mWho<span class="token punctuation">,</span> viewModelStore<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">return</span> viewModelStore<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// Fragment.getDefaultViewModelProviderFactory</span>
<span class="token comment">// ComponentActivity.getDefaultViewModelProviderFactory</span>
<span class="token comment">// 这两个的实现差不多，都会创建 SavedStateViewModelFactory 对象</span>
  <span class="token annotation punctuation">@NonNull</span>
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token class-name">ViewModelProvider<span class="token punctuation">.</span>Factory</span> <span class="token function">getDefaultViewModelProviderFactory</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// ... some code </span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>mDefaultFactory <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            mDefaultFactory <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">SavedStateViewModelFactory</span><span class="token punctuation">(</span>
                    <span class="token function">getApplication</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
                    <span class="token keyword">this</span><span class="token punctuation">,</span>
                    <span class="token function">getIntent</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">!=</span> <span class="token keyword">null</span> <span class="token operator">?</span> <span class="token function">getIntent</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getExtras</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">return</span> mDefaultFactory<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="viewmodelprovider-get-viewmodel-class" tabindex="-1"><a class="header-anchor" href="#viewmodelprovider-get-viewmodel-class" aria-hidden="true">#</a> viewModelProvider.get(ViewModel.class)</h3>
<p>get里面无非就是调用 factory.create 来创建对象ViewModel</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// ViewModelProvider.get()</span>
    <span class="token keyword">public</span> <span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span> <span class="token keyword">extends</span> <span class="token class-name">ViewModel</span><span class="token punctuation">></span></span> <span class="token class-name">T</span> <span class="token function">get</span><span class="token punctuation">(</span><span class="token annotation punctuation">@NonNull</span> <span class="token class-name">String</span> key<span class="token punctuation">,</span> <span class="token annotation punctuation">@NonNull</span> <span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span><span class="token punctuation">></span></span> modelClass<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token class-name">ViewModel</span> viewModel <span class="token operator">=</span> mViewModelStore<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>key<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// some code ... </span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>mFactory <span class="token keyword">instanceof</span> <span class="token class-name">KeyedFactory</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            viewModel <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token class-name">KeyedFactory</span><span class="token punctuation">)</span> <span class="token punctuation">(</span>mFactory<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span>key<span class="token punctuation">,</span> modelClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            viewModel <span class="token operator">=</span> <span class="token punctuation">(</span>mFactory<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span>modelClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        mViewModelStore<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span>key<span class="token punctuation">,</span> viewModel<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token class-name">T</span><span class="token punctuation">)</span> viewModel<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="savedstateviewmodelfactory-create-key-modelclass" tabindex="-1"><a class="header-anchor" href="#savedstateviewmodelfactory-create-key-modelclass" aria-hidden="true">#</a> SavedStateViewModelFactory.create(key, modelClass)</h3>
<ul>
<li><code v-pre>ProductViewModel</code> 继承于 <code v-pre>AndroidViewModel</code></li>
<li><code v-pre>findMatchingConstructor</code> 是用来判断是否存在 两个参数的构造器 <code v-pre>(Application, SavedStateHandle)</code></li>
<li>如果有会带入 <code v-pre>SavedStateHandle</code> 这个对象 也就是 <code v-pre>SavedStateHandleController.getHandle()</code></li>
</ul>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code> <span class="token keyword">public</span> <span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span> <span class="token keyword">extends</span> <span class="token class-name">ViewModel</span><span class="token punctuation">></span></span> <span class="token class-name">T</span> <span class="token function">create</span><span class="token punctuation">(</span><span class="token annotation punctuation">@NonNull</span> <span class="token class-name">String</span> key<span class="token punctuation">,</span> <span class="token annotation punctuation">@NonNull</span> <span class="token class-name">Class</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span><span class="token punctuation">></span></span> modelClass<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">boolean</span> isAndroidViewModel <span class="token operator">=</span> <span class="token class-name">AndroidViewModel</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">.</span><span class="token function">isAssignableFrom</span><span class="token punctuation">(</span>modelClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name">Constructor</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">T</span><span class="token punctuation">></span></span> constructor<span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>isAndroidViewModel<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            constructor <span class="token operator">=</span> <span class="token function">findMatchingConstructor</span><span class="token punctuation">(</span>modelClass<span class="token punctuation">,</span> <span class="token constant">ANDROID_VIEWMODEL_SIGNATURE</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            constructor <span class="token operator">=</span> <span class="token function">findMatchingConstructor</span><span class="token punctuation">(</span>modelClass<span class="token punctuation">,</span> <span class="token constant">VIEWMODEL_SIGNATURE</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token comment">// doesn't need SavedStateHandle</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>constructor <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> mFactory<span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span>modelClass<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>

        <span class="token class-name">SavedStateHandleController</span> controller <span class="token operator">=</span> <span class="token class-name">SavedStateHandleController</span><span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span>
                mSavedStateRegistry<span class="token punctuation">,</span> mLifecycle<span class="token punctuation">,</span> key<span class="token punctuation">,</span> mDefaultArgs<span class="token punctuation">)</span><span class="token punctuation">;</span>
           <span class="token comment">/// some code ... </span>
            <span class="token class-name">T</span> viewmodel<span class="token punctuation">;</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>isAndroidViewModel<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                viewmodel <span class="token operator">=</span> constructor<span class="token punctuation">.</span><span class="token function">newInstance</span><span class="token punctuation">(</span>mApplication<span class="token punctuation">,</span> controller<span class="token punctuation">.</span><span class="token function">getHandle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
                viewmodel <span class="token operator">=</span> constructor<span class="token punctuation">.</span><span class="token function">newInstance</span><span class="token punctuation">(</span>controller<span class="token punctuation">.</span><span class="token function">getHandle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            viewmodel<span class="token punctuation">.</span><span class="token function">setTagIfAbsent</span><span class="token punctuation">(</span><span class="token constant">TAG_SAVED_STATE_HANDLE_CONTROLLER</span><span class="token punctuation">,</span> controller<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">return</span> viewmodel<span class="token punctuation">;</span>
        <span class="token comment">/// some code ... </span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>整个ViewModel的创建 无非就是使用了工厂模式，在Fragment和Activity中实现了工厂，
但是对象被创建出来了，折腾了这么大一个圈子，然后怎么使用呢？</li>
<li>官网的设计ViewModel理念是： ViewModel 类旨在以注重生命周期的方式存储和管理界面相关的数据。ViewModel 类让数据可在发生屏幕旋转等配置更改后继续存在。<strong>那么是如何发挥这个作用的呢？</strong></li>
</ul>
<h3 id="viewmodelstore-带来的存储" tabindex="-1"><a class="header-anchor" href="#viewmodelstore-带来的存储" aria-hidden="true">#</a> ViewModelStore 带来的存储</h3>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// Activity.onRetainNonConfigurationInstance()</span>
<span class="token comment">// 这个函数的解释是说 在config和页面destory的时候回调用这个方法，CompotentActivity 重写了这个方法 把 viewModelStore 缓存起来了,然后页面重建后 会通过 getLastNonConfigurationInstance() 来获取 </span>
<span class="token comment">/*Called by the system, as part of destroying an
* activity due to a configuration change, when it is known that a new
* instance will immediately be created for the new configuration.  You
* can return any object you like here, including the activity instance
* itself, which can later be retrieved by calling
* {@link #getLastNonConfigurationInstance()} in the new activity
* instance.
*/</span>
<span class="token keyword">public</span> <span class="token keyword">final</span> <span class="token class-name">Object</span> <span class="token function">onRetainNonConfigurationInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token class-name">Object</span> custom <span class="token operator">=</span> <span class="token function">onRetainCustomNonConfigurationInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token class-name">ViewModelStore</span> viewModelStore <span class="token operator">=</span> mViewModelStore<span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>viewModelStore <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// No one called getViewModelStore(), so see if there was an existing</span>
        <span class="token comment">// ViewModelStore from our last NonConfigurationInstance</span>
        <span class="token class-name">NonConfigurationInstances</span> nc <span class="token operator">=</span>
                <span class="token punctuation">(</span><span class="token class-name">NonConfigurationInstances</span><span class="token punctuation">)</span> <span class="token function">getLastNonConfigurationInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>nc <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            viewModelStore <span class="token operator">=</span> nc<span class="token punctuation">.</span>viewModelStore<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">if</span> <span class="token punctuation">(</span>viewModelStore <span class="token operator">==</span> <span class="token keyword">null</span> <span class="token operator">&amp;&amp;</span> custom <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token class-name">NonConfigurationInstances</span> nci <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">NonConfigurationInstances</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    nci<span class="token punctuation">.</span>custom <span class="token operator">=</span> custom<span class="token punctuation">;</span>
    nci<span class="token punctuation">.</span>viewModelStore <span class="token operator">=</span> viewModelStore<span class="token punctuation">;</span>
    <span class="token keyword">return</span> nci<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


